'use client';
import { useEffect, useRef, useState, useCallback } from "react";
import Link from "next/link";

const GRID = 1000;
const PX   = 1;
const BASE_EARN = 5;
const HOLD_REWARD_RATE = 0.5 / 3600;

// ── SOL Economy ──────────────────────────────────────────────────────────────
const PIXEL_COST_SOL  = 0.001;          // SOL per placement
const SOL_START       = 20;             // demo starting balance
// Prize table — 97% RTP (EV = 0.00097 SOL per 0.001 SOL bet)
const SOL_PRIZES = [
  { mult: 0,   label: "—",     prob: 0.380 },  // 38% loss
  { mult: 0.5, label: "0.5×",  prob: 0.250 },  // 25% tiny
  { mult: 1.0, label: "1×",    prob: 0.190 },  // 19% break-even
  { mult: 2.0, label: "2×",    prob: 0.110 },  // 11% double
  { mult: 5.0, label: "5×",    prob: 0.055 },  // 5.5% big
  { mult: 10.0,label: "10×",   prob: 0.015 },  // 1.5% max
] as const;
// Bucket jackpot
const BUCKET_WIN_CHANCE = 0.005;        // 0.5% per placement
const BUCKET_WIN_PCT    = 0.10;         // win 10% of bucket
const BUCKET_FEED_PCT   = 0.01;         // 1% of CANVAS earn → bucket

const BET_TIERS = [
  { sol: 0.01, pixels: 1,   label: "0.01 SOL",  tag: "×1"  },
  { sol: 0.1,  pixels: 10,  label: "0.1 SOL",   tag: "×10" },
  { sol: 1.0,  pixels: 100, label: "1 SOL",      tag: "×100"},
] as const;
type BetIdx = 0 | 1 | 2;

function rollSolPrize(): { mult: number; label: string } {
  let r = Math.random();
  for (const p of SOL_PRIZES) {
    r -= p.prob;
    if (r <= 0) return p;
  }
  return SOL_PRIZES[0];
}

const PALETTE = [
  "#ef4444","#f97316","#f59e0b","#84cc16",
  "#22c55e","#06b6d4","#3b82f6","#6366f1",
  "#8b5cf6","#ec4899","#f43f5e","#ffffff",
  "#e2e8f0","#94a3b8","#475569","#1e293b",
];

type StrikeTier = "none"|"common"|"rare"|"legendary";
interface PxData { color: string; owner: string; }

function rollStrike(): StrikeTier {
  const r = Math.random();
  if (r < 0.001) return "legendary";
  if (r < 0.01)  return "rare";
  if (r < 0.05)  return "common";
  return "none";
}
function strikeBonus(t: StrikeTier) { return t==="legendary"?200:t==="rare"?25:t==="common"?5:1; }
function strikeStyle(t: StrikeTier): {bg:string;border:string;text:string;shadow:string} {
  if (t==="legendary") return {bg:"#1c0f00",border:"#f59e0b",text:"#fbbf24",shadow:"rgba(245,158,11,0.8)"};
  if (t==="rare")      return {bg:"#0c1a2e",border:"#22d3ee",text:"#67e8f9",shadow:"rgba(34,211,238,0.6)"};
  return                      {bg:"#12121a",border:"#64748b",text:"#94a3b8",shadow:"rgba(100,116,139,0.4)"};
}

const BOTS = ["0x7a3…b9f","0xaf1…c32","0x99d…441","0xb82…71a","0x55e…f90","0xcc4…d18"];
const rndOwner = () => BOTS[Math.floor(Math.random()*BOTS.length)];
const WALLET = "YOU (Demo_7f4…a9c)";

// ─── Pixel Art Seeding ────────────────────────────────────────────────────────

function px(g: (PxData|null)[], x: number, y: number, color: string, owner = "art") {
  if (x >= 0 && x < GRID && y >= 0 && y < GRID)
    g[y * GRID + x] = { color, owner };
}

function fillRect(g: (PxData|null)[], x: number, y: number, w: number, h: number, color: string) {
  for (let dy = 0; dy < h; dy++)
    for (let dx = 0; dx < w; dx++)
      px(g, x + dx, y + dy, color);
}

function drawPattern(
  g: (PxData|null)[],
  ox: number, oy: number,
  rows: string[],
  palette: Record<string, string>
) {
  rows.forEach((row, dy) =>
    [...row].forEach((ch, dx) => {
      const c = palette[ch];
      if (c) px(g, ox + dx, oy + dy, c);
    })
  );
}

function seedCanvas(g: (PxData|null)[]) {

  // ZONE BACKGROUNDS
  fillRect(g,   0,   0, 480, 490, "#1c0900");
  fillRect(g, 520,   0, 480, 330, "#0c0018");
  fillRect(g,   0, 520, 310, 480, "#001a04");
  fillRect(g, 520, 520, 480, 480, "#120a00");
  fillRect(g, 310,   0, 210, 240, "#1a0000");
  fillRect(g, 310, 520, 210, 480, "#001018");
  fillRect(g, 480,   0,  40, 1000, "#050505");
  fillRect(g,   0, 480, 1000, 40, "#050505");
  fillRect(g, 310, 240, 210, 240, "#050a05");

  // 1. LARGE BITCOIN COIN (top-left)
  drawPattern(g, 135, 135, ["................................................................................G................................................................................","....................................................................GGGGGGGGGGGGGGGGGGGGGGGGG....................................................................","...............................................................GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG...............................................................","...........................................................GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG...........................................................","........................................................GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG........................................................",".....................................................GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG.....................................................","..................................................GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG..................................................","................................................GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGDGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG................................................","..............................................GGGGGGGGGGGGGGGGGGGGGGDDDDDDDDDDDDDDDDDDDDDDDDDGGGGGGGGGGGGGGGGGGGGGG..............................................","............................................GGGGGGGGGGGGGGGGGGGGDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDGGGGGGGGGGGGGGGGGGGG............................................","..........................................GGGGGGGGGGGGGGGGGGDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDGGGGGGGGGGGGGGGGGG..........................................","........................................GGGGGGGGGGGGGGGGGDDDDDDDDDDDDDDDDDDDDDDDODDDDDDDDDDDDDDDDDDDDDDDGGGGGGGGGGGGGGGGG........................................","......................................GGGGGGGGGGGGGGGGDDDDDDDDDDDDDDDVVVOOOOOOOOOOOOOOOOOOOODDDDDDDDDDDDDDDGGGGGGGGGGGGGGGG......................................",".....................................GGGGGGGGGGGGGGGDDDDDDDDDDDDOOOOVVVVOOOOOOOOOOOOOOOOOOOOOOOOODDDDDDDDDDDDGGGGGGGGGGGGGGG.....................................","...................................GGGGGGGGGGGGGGDDDDDDDDDDDOOOOOOOOVVVVOOOOOOOOOOOOOOOOOOOOOOOOOOOOODDDDDDDDDDDGGGGGGGGGGGGGG...................................","..................................GGGGGGGGGGGGGDDDDDDDDDDOOOOOOOOOOOVVVVOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOODDDDDDDDDDGGGGGGGGGGGGG..................................","................................GGGGGGGGGGGGGDDDDDDDDDDOOOOOOOOOOOOOVVVVOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOODDDDDDDDDDGGGGGGGGGGGGG................................","...............................GGGGGGGGGGGGGDDDDDDDDOOOOOOOOOOOOOOOOVVVVOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOODDDDDDDDGGGGGGGGGGGGG...............................","..............................GGGGGGGGGGGGDDDDDDDDOOOOOOOOOOOOOOOOOOVVVVOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOODDDDDDDDGGGGGGGGGGGG..............................",".............................GGGGGGGGGGGDDDDDDDDOOOOOOOOOOOOOOOOOOOOVVVVOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOODDDDDDDDGGGGGGGGGGG.............................","............................GGGGGGGGGGGDDDDDDDOOOOOOOOOOOOOOOOOOOOOOVVVVOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOODDDDDDDGGGGGGGGGGG............................","..........................GGGGGGGGGGGGDDDDDDDOOOOOOOOOOOOOOOOOOOOOOOVVVVOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOODDDDDDDGGGGGGGGGGGG..........................",".........................GGGGGGGGGGGDDDDDDDOOOOOOOOOOOOOOOOOOOOOOOOOVVVVOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOODDDDDDDGGGGGGGGGGG.........................","........................GGGGGGGGGGGDDDDDDDOOOOOOOOOOOOOOOOOOOOOOOOOOVVVVOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOODDDDDDDGGGGGGGGGGG........................",".......................GGGGGGGGGGGDDDDDDOOOOOOOOOOOOOOOOOOOOOOOOOOOOVVVVOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOODDDDDDGGGGGGGGGGG.......................","......................GGGGGGGGGGDDDDDDDOOOOOOOOOOOOOOOOOOOOOOOOOOOOOVVVVOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOODDDDDDDGGGGGGGGGG......................",".....................GGGGGGGGGGDDDDDDDOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOVVVVOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOODDDDDDDGGGGGGGGGG.....................",".....................GGGGGGGGGDDDDDDOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOVVVVOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOODDDDDDGGGGGGGGG.....................","....................GGGGGGGGGDDDDDDOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOVVVVOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOODDDDDDGGGGGGGGG....................","...................GGGGGGGGGDDDDDDOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOVVVVOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOODDDDDDGGGGGGGGG...................","..................GGGGGGGGGDDDDDDOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOVVVVOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOODDDDDDGGGGGGGGG..................",".................GGGGGGGGGDDDDDDOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOVVVVOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOODDDDDDGGGGGGGGG.................","................GGGGGGGGGDDDDDDOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOVVVVOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOODDDDDDGGGGGGGGG................","................GGGGGGGGGDDDDDOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOVVVVOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOODDDDDGGGGGGGGG................","...............GGGGGGGGGDDDDDOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOVVVVOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOODDDDDGGGGGGGGG...............","..............GGGGGGGGGDDDDDOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOVVVVOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOODDDDDGGGGGGGGG..............","..............GGGGGGGGDDDDDOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOVVVVOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOODDDDDGGGGGGGG..............",".............GGGGGGGGGDDDDDOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOVVVVOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOODDDDDGGGGGGGGG.............","............GGGGGGGGGDDDDDOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOVVVVOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOODDDDDGGGGGGGGG............","............GGGGGGGGDDDDDOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOVVVVOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOODDDDDGGGGGGGG............","...........GGGGGGGGDDDDDOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOVVVVOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOODDDDDGGGGGGGG...........","...........GGGGGGGGDDDDDOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOVVVVOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOODDDDDGGGGGGGG...........","..........GGGGGGGGDDDDDOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOVVVVOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOODDDDDGGGGGGGG..........","..........GGGGGGGGDDDDOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOVVVVOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOODDDDGGGGGGGG..........",".........GGGGGGGGDDDDDOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOVVVVOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOODDDDDGGGGGGGG.........",".........GGGGGGGDDDDDOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOVVVVOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOODDDDDGGGGGGG.........","........GGGGGGGGDDDDOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOVVVVOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOODDDDGGGGGGGG........","........GGGGGGGDDDDDOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOVVVVOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOODDDDDGGGGGGG........",".......GGGGGGGGDDDDOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOVVVVOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOODDDDGGGGGGGG.......",".......GGGGGGGDDDDDOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOVVVVOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOODDDDDGGGGGGG.......","......GGGGGGGGDDDDOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOVVVVOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOODDDDGGGGGGGG......","......GGGGGGGGDDDDOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOVVVVOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOODDDDGGGGGGGG......","......GGGGGGGDDDDOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOVVVVOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOODDDDGGGGGGG......",".....GGGGGGGGDDDDOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOVVVVOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOODDDDGGGGGGGG.....",".....GGGGGGGDDDDDOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOVVVVOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOODDDDDGGGGGGG.....",".....GGGGGGGDDDDOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOVVVVOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOODDDDGGGGGGG.....","....GGGGGGGGDDDDOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOVVVVOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOODDDDGGGGGGGG....","....GGGGGGGDDDDOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOVVVVOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOODDDDGGGGGGG....","....GGGGGGGDDDDOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOVVVVOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOODDDDGGGGGGG....","...GGGGGGGGDDDDOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOVVVVOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOODDDDGGGGGGGG...","...GGGGGGGDDDDOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOVVVVOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOODDDDGGGGGGG...","...GGGGGGGDDDDOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOVVVVOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOODDDDGGGGGGG...","...GGGGGGGDDDDOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOVVVVVVVVVVVVVVVVVVVVVOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOODDDDGGGGGGG...","..GGGGGGGGDDDDOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOVVVVOOOOOOOOVVVVVVVVVVOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOODDDDGGGGGGGG..","..GGGGGGGDDDDOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOVVVVOOOOOOOOVVVVVVVVVVVOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOODDDDGGGGGGG..","..GGGGGGGDDDDOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOVOOOOOOOOOOOOOVVVVVVVVVOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOODDDDGGGGGGG..","..GGGGGGGDDDDOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOVOOOOOOOOOOOOOVVVVVVVVVOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOODDDDGGGGGGG..","..GGGGGGGDDDDOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOVOOOOOOOOOOOOOVVVVVVVVVOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOODDDDGGGGGGG..",".GGGGGGGDDDDDOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOVOOOOOOOOOOOOOVVVVVVVVVOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOODDDDDGGGGGGG.",".GGGGGGGDDDDOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOVOOOOOOOOOOOOOVVVVVVVVVOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOODDDDGGGGGGG.",".GGGGGGGDDDDOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOVOOOOOOOOOOOOOVVVVVVVVVOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOODDDDGGGGGGG.",".GGGGGGGDDDDOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOVOOOOOOOOOOOOOVVVVVVVVVOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOODDDDGGGGGGG.",".GGGGGGGDDDDOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOVOOOOOOOOOOOOOVVVVVVVVVOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOODDDDGGGGGGG.",".GGGGGGGDDDDOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOVOOOOOOOOOOOOOVVVVVVVVVOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOODDDDGGGGGGG.",".GGGGGGGDDDDOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOVOOOOOOOOOOOOOVVVVVVVVVOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOODDDDGGGGGGG.",".GGGGGGGDDDDOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOVOOOOOOOOOOOOOVVVVVVVVVOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOODDDDGGGGGGG.",".GGGGGGGDDDDOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOVOOOOOOOOOOOOOVVVVVVVVVOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOODDDDGGGGGGG.",".GGGGGGGDDDDOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOVOOOOOOOOOOOOOVVVVVVVVOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOODDDDGGGGGGG.",".GGGGGGGDDDDOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOVOOOOOOOOOOOOOVVVVVVVOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOODDDDGGGGGGG.",".GGGGGGGDDDDOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOVVVVVVVVVVVVVVVVVVVVVOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOODDDDGGGGGGG.","GGGGGGGDDDDOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOVVVVVVVVVVVVVVVVVVVVVOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOODDDDGGGGGGG",".GGGGGGGDDDDOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOVVVVVVVVVVVVVVVVVVVVVOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOODDDDGGGGGGG.",".GGGGGGGDDDDOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOVVVVOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOODDDDGGGGGGG.",".GGGGGGGDDDDOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOVVVVOOOOOOOOVVVVVVVVVVOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOODDDDGGGGGGG.",".GGGGGGGDDDDOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOVVVVOOOOOOOOVVVVVVVVVVVOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOODDDDGGGGGGG.",".GGGGGGGDDDDOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOVOOOOOOOOOOOOOVVVVVVVVVVOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOODDDDGGGGGGG.",".GGGGGGGDDDDOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOVOOOOOOOOOOOOOVVVVVVVVVVVOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOODDDDGGGGGGG.",".GGGGGGGDDDDOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOVOOOOOOOOOOOOOVVVVVVVVVVVOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOODDDDGGGGGGG.",".GGGGGGGDDDDOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOVOOOOOOOOOOOOOVVVVVVVVVVVOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOODDDDGGGGGGG.",".GGGGGGGDDDDOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOVOOOOOOOOOOOOOVVVVVVVVVVVOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOODDDDGGGGGGG.",".GGGGGGGDDDDOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOVOOOOOOOOOOOOOVVVVVVVVVVVOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOODDDDGGGGGGG.",".GGGGGGGDDDDOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOVOOOOOOOOOOOOOVVVVVVVVVVVOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOODDDDGGGGGGG.",".GGGGGGGDDDDDOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOVOOOOOOOOOOOOOVVVVVVVVVVVOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOODDDDDGGGGGGG.","..GGGGGGGDDDDOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOVOOOOOOOOOOOOOVVVVVVVVVVVOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOODDDDGGGGGGG..","..GGGGGGGDDDDOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOVOOOOOOOOOOOOOVVVVVVVVVVVOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOODDDDGGGGGGG..","..GGGGGGGDDDDOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOVOOOOOOOOOOOOOVVVVVVVVVVVOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOODDDDGGGGGGG..","..GGGGGGGDDDDOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOVOOOOOOOOOOOOOVVVVVVVVVVVOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOODDDDGGGGGGG..","..GGGGGGGGDDDDOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOVOOOOOOOOOOOOOVVVVVVVVVVVOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOODDDDGGGGGGGG..","...GGGGGGGDDDDOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOVOOOOOOOOOOOOOVVVVVVVVVVVOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOODDDDGGGGGGG...","...GGGGGGGDDDDOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOVOOOOOOOOOOOOOVVVVVVVVVVOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOODDDDGGGGGGG...","...GGGGGGGDDDDOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOVVVVVVVVVVVVVVVVVVVVVVVOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOODDDDGGGGGGG...","...GGGGGGGGDDDDOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOVVVVOOOOOOOOVVVVVVVVVVOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOODDDDGGGGGGGG...","....GGGGGGGDDDDOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOVVVVOOOOOOOOOVVVVVVVOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOODDDDGGGGGGG....","....GGGGGGGDDDDOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOVVVVOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOODDDDGGGGGGG....","....GGGGGGGGDDDDOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOVVVVOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOODDDDGGGGGGGG....",".....GGGGGGGDDDDOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOVVVVOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOODDDDGGGGGGG.....",".....GGGGGGGDDDDDOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOVVVVOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOODDDDDGGGGGGG.....",".....GGGGGGGGDDDDOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOVVVVOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOODDDDGGGGGGGG.....","......GGGGGGGDDDDOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOVVVVOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOODDDDGGGGGGG......","......GGGGGGGGDDDDOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOVVVVOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOODDDDGGGGGGGG......","......GGGGGGGGDDDDOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOVVVVOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOODDDDGGGGGGGG......",".......GGGGGGGDDDDDOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOVVVVOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOODDDDDGGGGGGG.......",".......GGGGGGGGDDDDOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOVVVVOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOODDDDGGGGGGGG.......","........GGGGGGGDDDDDOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOVVVVOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOODDDDDGGGGGGG........","........GGGGGGGGDDDDOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOVVVVOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOODDDDGGGGGGGG........",".........GGGGGGGDDDDDOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOVVVVOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOODDDDDGGGGGGG.........",".........GGGGGGGGDDDDDOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOVVVVOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOODDDDDGGGGGGGG.........","..........GGGGGGGGDDDDOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOVVVVOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOODDDDGGGGGGGG..........","..........GGGGGGGGDDDDDOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOVVVVOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOODDDDDGGGGGGGG..........","...........GGGGGGGGDDDDDOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOVVVVOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOODDDDDGGGGGGGG...........","...........GGGGGGGGDDDDDOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOVVVVOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOODDDDDGGGGGGGG...........","............GGGGGGGGDDDDDOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOVVVVOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOODDDDDGGGGGGGG............","............GGGGGGGGGDDDDDOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOVVVVOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOODDDDDGGGGGGGGG............",".............GGGGGGGGGDDDDDOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOVVVVOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOODDDDDGGGGGGGGG.............","..............GGGGGGGGDDDDDOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOVVVVOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOODDDDDGGGGGGGG..............","..............GGGGGGGGGDDDDDOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOVVVVOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOODDDDDGGGGGGGGG..............","...............GGGGGGGGGDDDDDOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOVVVVOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOODDDDDGGGGGGGGG...............","................GGGGGGGGGDDDDDOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOVVVVOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOODDDDDGGGGGGGGG................","................GGGGGGGGGDDDDDDOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOVVVVOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOODDDDDDGGGGGGGGG................",".................GGGGGGGGGDDDDDDOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOVVVVOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOODDDDDDGGGGGGGGG.................","..................GGGGGGGGGDDDDDDOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOVVVVOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOODDDDDDGGGGGGGGG..................","...................GGGGGGGGGDDDDDDOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOVVVVOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOODDDDDDGGGGGGGGG...................","....................GGGGGGGGGDDDDDDOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOVVVVOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOODDDDDDGGGGGGGGG....................",".....................GGGGGGGGGDDDDDDOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOVVVVOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOODDDDDDGGGGGGGGG.....................",".....................GGGGGGGGGGDDDDDDDOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOVVVVOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOODDDDDDDGGGGGGGGGG.....................","......................GGGGGGGGGGDDDDDDDOOOOOOOOOOOOOOOOOOOOOOOOOOOOOVVVVOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOODDDDDDDGGGGGGGGGG......................",".......................GGGGGGGGGGGDDDDDDOOOOOOOOOOOOOOOOOOOOOOOOOOOOVVVVOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOODDDDDDGGGGGGGGGGG.......................","........................GGGGGGGGGGGDDDDDDDOOOOOOOOOOOOOOOOOOOOOOOOOOVVVVOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOODDDDDDDGGGGGGGGGGG........................",".........................GGGGGGGGGGGDDDDDDDOOOOOOOOOOOOOOOOOOOOOOOOOVVVVOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOODDDDDDDGGGGGGGGGGG.........................","..........................GGGGGGGGGGGGDDDDDDDOOOOOOOOOOOOOOOOOOOOOOOVVVVOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOODDDDDDDGGGGGGGGGGGG..........................","............................GGGGGGGGGGGDDDDDDDOOOOOOOOOOOOOOOOOOOOOOVVVVOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOODDDDDDDGGGGGGGGGGG............................",".............................GGGGGGGGGGGDDDDDDDDOOOOOOOOOOOOOOOOOOOOVVVVOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOODDDDDDDDGGGGGGGGGGG.............................","..............................GGGGGGGGGGGGDDDDDDDDOOOOOOOOOOOOOOOOOOVVVVOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOODDDDDDDDGGGGGGGGGGGG..............................","...............................GGGGGGGGGGGGGDDDDDDDDOOOOOOOOOOOOOOOOVVVVOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOODDDDDDDDGGGGGGGGGGGGG...............................","................................GGGGGGGGGGGGGDDDDDDDDDDOOOOOOOOOOOOOVVVVOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOODDDDDDDDDDGGGGGGGGGGGGG................................","..................................GGGGGGGGGGGGGDDDDDDDDDDOOOOOOOOOOOVVVVOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOODDDDDDDDDDGGGGGGGGGGGGG..................................","...................................GGGGGGGGGGGGGGDDDDDDDDDDDOOOOOOOOVVVVOOOOOOOOOOOOOOOOOOOOOOOOOOOOODDDDDDDDDDDGGGGGGGGGGGGGG...................................",".....................................GGGGGGGGGGGGGGGDDDDDDDDDDDDOOOOVVVVOOOOOOOOOOOOOOOOOOOOOOOOODDDDDDDDDDDDGGGGGGGGGGGGGGG.....................................","......................................GGGGGGGGGGGGGGGGDDDDDDDDDDDDDDDVVVOOOOOOOOOOOOOOOOOOOODDDDDDDDDDDDDDDGGGGGGGGGGGGGGGG......................................","........................................GGGGGGGGGGGGGGGGGDDDDDDDDDDDDDDDDDDDDDDDODDDDDDDDDDDDDDDDDDDDDDDGGGGGGGGGGGGGGGGG........................................","..........................................GGGGGGGGGGGGGGGGGGDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDGGGGGGGGGGGGGGGGGG..........................................","............................................GGGGGGGGGGGGGGGGGGGGDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDGGGGGGGGGGGGGGGGGGGG............................................","..............................................GGGGGGGGGGGGGGGGGGGGGGDDDDDDDDDDDDDDDDDDDDDDDDDGGGGGGGGGGGGGGGGGGGGGG..............................................","................................................GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGDGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG................................................","..................................................GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG..................................................",".....................................................GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG.....................................................","........................................................GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG........................................................","...........................................................GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG...........................................................","...............................................................GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG...............................................................","....................................................................GGGGGGGGGGGGGGGGGGGGGGGGG....................................................................","................................................................................G................................................................................"], {"G":"#f59e0b","D":"#92400e","O":"#f97316","V":"#7c2d12"}); // BTC coin
  drawPattern(g, 193, 308, ["BBBBB.TTTTT.CCCCC","B...B...T...C....","BBBBB...T...C....","B...B...T...C....","BBBBB.TTTTT.CCCCC"], {"B":"#f59e0b","T":"#f59e0b","C":"#f59e0b"}); // BTC label
  drawPattern(g, 20, 430, ["H...H.OOO.DDD..LLL","HHHHH.O.O.D..D.L..","H...H.OOO.DDD..LLL"], {"H":"#f59e0b","O":"#f59e0b","D":"#f59e0b","L":"#f59e0b"}); // HODL
  drawPattern(g, 20, 20, ["SSS.AAA.TTT.OOO.SSS.HHH.III","S...A.A..T..O.O.S...H.H..I.","SSS.AAA..T..O.O.S...HHH..I.","..S.A.A..T..O.O.S...H.H..I.","SSS.A.A..T..OOO.SSS.H.H.III"], {"S":"#f59e0b","A":"#f59e0b","T":"#f59e0b","O":"#f59e0b","H":"#f59e0b","I":"#f59e0b"}); // SATOSHI

  // 2. ETH DIAMOND (top-right)
  drawPattern(g, 725, 25, ["......................................................................","..................................LL..................................",".................................LLLL.................................","................................LLLLLL................................","...............................LLLLLLLL...............................","..............................LLLLLLLLLL..............................","............................LLLLLLLLLLLLLL............................","...........................LLLLLLLLLLLLLLLL...........................","..........................LLLLLLLLLLLLLLLLLL..........................",".........................LLLLLLLLLLLLLLLLLLLL.........................","........................LLLLLLLLLLLLLLLLLLLLLL........................",".......................LLLLLLLLLLLLLLLLLLLLLLLL.......................",".....................LLLLLLLLLLLLLLLLLLLLLLLLLLLL.....................","....................LLLLLLLLLLLLLLLLLLLLLLLLLLLLLL....................","...................LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL...................","..................MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM..................",".................MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.................","................MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM................","..............MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM..............",".............MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.............","............MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM............","...........MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM...........","..........MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM..........",".........MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.........",".......MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.......","......MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM......",".....MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.....","....MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM....","...MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM...","..MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM..","MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",".MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.","..MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM..","...MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM...","....MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM....",".....MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.....",".......MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.......","........MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM........",".........MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.........","..........MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM..........","...........MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM...........","............MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM............","..............MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM..............","...............MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM...............","................MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM................",".................MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.................","..................MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM..................","...................MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM...................",".....................MMMMMMMMMMMMMMMMMMMMMMMMMMMM.....................","......................MMMMMMMMMMMMMMMMMMMMMMMMMM......................",".......................MMMMMMMMMMMMMMMMMMMMMMMM.......................","........................MMMMMMMMMMMMMMMMMMMMMM........................",".........................MMMMMMMMMMMMMMMMMMMM.........................","..........................MMMMMMMMMMMMMMMMMM..........................","............................MMMMMMMMMMMMMM............................",".............................MMMMMMMMMMMM.............................","..............................MMMMMMMMMM..............................","...............................MMMMMMMM...............................","................................MMMMMM................................",".................................MMMM.................................","DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",".DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD.","..DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD..","...DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD...","....DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD....",".....DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD.....",".......DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD.......","........DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD........",".........DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD.........","..........DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD..........","...........DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD...........","............DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD............","..............DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD..............","...............DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD...............","................DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD................",".................DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD.................","..................DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD..................","...................DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD...................",".....................DDDDDDDDDDDDDDDDDDDDDDDDDDDD.....................","......................DDDDDDDDDDDDDDDDDDDDDDDDDD......................",".......................DDDDDDDDDDDDDDDDDDDDDDDD.......................","........................DDDDDDDDDDDDDDDDDDDDDD........................",".........................DDDDDDDDDDDDDDDDDDDD.........................","..........................DDDDDDDDDDDDDDDDDD..........................","............................DDDDDDDDDDDDDD............................",".............................DDDDDDDDDDDD.............................","..............................DDDDDDDDDD..............................","...............................DDDDDDDD...............................","................................DDDDDD................................",".................................DDDD.................................","......................................................................","..................................VV..................................",".................................VVVV.................................","................................VVVVVV................................","...............................VVVVVVVV...............................","..............................VVVVVVVVVV..............................","............................VVVVVVVVVVVVVV............................","...........................VVVVVVVVVVVVVVVV...........................","..........................VVVVVVVVVVVVVVVVVV..........................",".........................VVVVVVVVVVVVVVVVVVVV.........................","........................VVVVVVVVVVVVVVVVVVVVVV........................",".......................VVVVVVVVVVVVVVVVVVVVVVVV.......................",".....................VVVVVVVVVVVVVVVVVVVVVVVVVVVV.....................","....................VVVVVVVVVVVVVVVVVVVVVVVVVVVVVV....................","...................VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV...................","..................VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV..................",".................VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV.................","................VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV................","..............VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV..............",".............VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV.............","............VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV............","...........VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV...........","..........VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV..........",".........VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV.........",".......VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV.......","......VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV......",".....VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV.....","....VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV....","...VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV...","..VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV.."], {"L":"#c084fc","M":"#9333ea","D":"#7c3aed","V":"#4c1d95"}); // ETH diamond
  drawPattern(g, 742, 152, ["EEE.TTT.HHH","E...TTT.H.H","EEE...T.HHH","E.....T.H.H","EEE...T.H.H"], {"E":"#9333ea","T":"#9333ea","H":"#9333ea"}); // ETH label
  drawPattern(g, 530, 60, ["GGG.AAA.SSS..FFF.EEE.EEE.SSS","G.G.A.A.S....F...E...E...S..","GGG.AAA.SSS..FFF.EEE.EEE.SSS","G.G.A.A...S..F...E...E...S..","G.G.A.A.SSS..F...EEE.EEE.SSS"], {"G":"#7c3aed","A":"#7c3aed","S":"#7c3aed","F":"#7c3aed","E":"#7c3aed"}); // GAS FEES
  drawPattern(g, 885, 50, ["..F.....",".FFF....","FFFFF...","FFFFFFFF",".FFFFFFF","..FFFFF.","...FFF..","....F..."], {"F":"#f97316"}); // burn flame

  // 3. TRUMP PORTRAIT (MAGA zone)
  drawPattern(g, 313, 5, ["......HHHHHHHHHHHHHHHHHHHH......","....HHHHHHHHHHHHHHHHHHHHHHHH....","...HHHHHHHHHHHHHHHHHHHHHHHHHH...","..HHHHHHHHHHHHHHHHHHHHHHHHHHHH..",".HHHHHHHHHHHHHHHHHHHHHHHHHHHHHH.","HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH.","HHHHHSSSSSSSSSSSSSSSSSSSSSSHHHHH","HSSSSSSSSSSSSSSSSSSSSSSSSSSSSSH.",".SSSSSSBBBBBBBBSSSBBBBBBBSSSSSS.",".SSSSSBBB....BBBSBB....BBBSSSSS.",".SSSSBB..EEEE.BBSBB.EEEE.BBSSSS.",".SSSSBB..EEEE.BBSBB.EEEE.BBSSSS.",".SSSSSBB......BSSBB......BSSSSS..",".SSSSSSSBBBBBBBSSSBBBBBBSSSSSSSS.",".SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS.",".SSSSSSSSS.NNNN.SSSSSSSSSSSSSSS..",".SSSSSSSSSS.NNNN.SSSSSSSSSSSSSS..",".SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS.",".SSSSSSSSSSRRRRRRRRRSSSSSSSSSSSS.",".SSSSSSSSSRRRRRRRRRRRSSSSSSSSSSS.",".SSSSSSSSSSRRRRRRRRRSSSSSSSSSSSS.",".SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS.","..WWWWWWWWWWWWWWWWWWWWWWWWWWWWW.","..WDDDDDDDDDDDRDDDDDDDDDDDDDDDW.","..DDDDDDDDDDRRRRRDDDDDDDDDDDDDD.","...DDDDDDDDRRRRRRRRDDDDDDDDDD...","....DDDDDDDRRRRRRRRDDDDDDDD.....",".....DDDDDDRRRRRRRRDDDDDDD......","......DDDDDRRRRRRRRDDDDDD.......",".......DDDDRRRRRRRRDDDDD........","........DDDRRRRRRRRDDDD.........",".........DDRRRRRRRRDDD..........","..........DRRRRRRRRD............"], {"H":"#f7a000","S":"#fddcb0","B":"#333","E":"#5588cc","N":"#cc9966","R":"#cc0000","W":"#f0f0f0","D":"#1a2060"}); // Trump portrait
  drawPattern(g, 322, 200, ["MMM.AAA.GGG.AAA","M.M.A.A.G.G.A.A","MMM.AAA.GGG.AAA","M.M.A.A.G.G.A.A","M.M.A.A.GGG.A.A"], {"M":"#cc0000","A":"#cc0000","G":"#cc0000"}); // MAGA

  // 4. ELON MUSK (ETH zone, right)
  drawPattern(g, 685, 155, ["....DDDDDDDDDDDDDDDDDDDDDDDDDD..","..DDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",".DDDDDDDDDDDDDDDDDDDDDDDDDDDDDD.","DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD.","DDDSSSSSSSSSSSSSSSSSSSSSSSSSDDD.",".DSSSSSSSSSSSSSSSSSSSSSSSSSSSD..","..SSSSSSBBBBBBBBSSSBBBBBBBSSSSS.","..SSSSSBB....BBBSBB....BBSSSSSS.","..SSSSSBB.EE.BBBSBB.EE.BBSSSSS.","..SSSSSBB.EE.BBBSBB.EE.BBSSSSS.","..SSSSSSBB...BBBSBB...BBSSSSSS..","..SSSSSSSBBBBBBBBSBBBBBBSSSSSSS.","..SSSSSSSSSSSSSSSSSSSSSSSSSSSS..","..SSSSSSS.NNNN.SSSSSSSSSSSSSS...","..SSSSSSSSNNNN.SSSSSSSSSSSSSSS..","..SSSSSSSSSSSSSSSSSSSSSSSSSSSS..","..SSSSSSSSMMMMMMMMSSSSSSSSSSS...","..SSSSSSSSMMMMMMMMSSSSSSSSSSS...","..SSSSSSSSSSSSSSSSSSSSSSSSSSSS..","...BBBBBBBBBBBBBBBBBBBBBBBBBB...","...BBBBBBBBBBBBBBBBBBBBBBBBBB...","....BBBBBBBBBBBBBBBBBBBBBBB.....",".....BBBBBBBBBBBBBBBBBBBBB......","......BBBBBBBBBBBBBBBBBBB......."], {"D":"#2d2020","S":"#ffdfbf","B":"#222","E":"#335577","N":"#cc9966","M":"#555"}); // Musk portrait
  drawPattern(g, 935, 162, ["X...X","X...X",".X.X.","..X..",".X.X.","X...X","X...X"], {"X":"#ffffff"}); // X logo
  drawPattern(g, 530, 170, ["..RRR..",".RRRRR.","RRRRRRR","RR.R.RR","RRRRRRR","RRRRRRR","RR.R.RR",".FF.FF.","FFF.FFF"], {"R":"#aaaaaa","F":"#f97316"}); // SpaceX rocket

  // 5. DOGE SHIBA INU (left zone)
  drawPattern(g, 18, 180, ["..TTTTTTTTTTTTTTTTTTTTTTTTTT..",".TTTTTTTTTTTTTTTTTTTTTTTTTTTT.","TTTTTTTTTTTTTTTTTTTTTTTTTTTTTT","TTTTTTTTTTTTTTTTTTTTTTTTTTTTTT","TTTSSSSSSSSSSSSSSSSSSSSSSSTTTT",".TSSSSSSSSSSSSSSSSSSSSSSSSSST.",".SSSSSSSSSSSSSSSSSSSSSSSSSSSSS",".SSSSSBBBBBBSSSSSSBBBBBBSSSSSS",".SSSSBB....BBSSSSBB....BBSSSSS",".SSSSBB.WW.BBSSSSBB.WW.BBSSSSS",".SSSSBB....BBSSSSBB....BBSSSSS",".SSSSSBBBBBBSSSSSSBBBBBBSSSSSS.",".SSSSSSSSSSSSSSSSSSSSSSSSSSSSSS",".SSSSSSSSSSSNN.NNNSSSSSSSSSSSSS",".SSSSSSSSSSNNNNNNNNSSSSSSSSSSSS",".SSSSSSSSSSNNNNNNNNSSSSSSSSSSSS",".SSSSSSSSSSSNN.NNNSSSSSSSSSSSSS",".SSSSSSSSSSSSSSSSSSSSSSSSSSSSS.",".SWWWWWWWWWWWWWWWWWWWWWWWWWWWS",".SWWWWWWWWWWWWWWWWWWWWWWWWWWWS",".SWWWWWWRRRRRRRRRRRWWWWWWWWWWS.",".SWWWWWWRRRRRRRRRRRWWWWWWWWWWS.",".SWWWWWWWWWWWWWWWWWWWWWWWWWWWS.","..SSSSSSSSSSSSSSSSSSSSSSSSSSS..","...TTTTTTTTTTTTTTTTTTTTTTTTT...","....TTTTTTTTTTTTTTTTTTTTTTT...."], {"T":"#c8922a","S":"#f5d898","B":"#333","W":"#fff","N":"#aa6600","R":"#cc3333"}); // Doge face
  drawPattern(g, 22, 100, ["W...W.OOO.W...W","W...W.O.O.W...W","W.W.W.O.O.W.W.W","W.W.W.O.O.W.W.W",".W.W..OOO..W.W."], {"W":"#c8922a","O":"#c8922a"}); // WOW
  drawPattern(g, 22, 420, ["MMM.U.U.CCC.H...H","M.M.U.U.C...H.H.H","MMM.U.U.C...HHHHH","M.M.U.U.C...H...H","M.M.UUU.CCC.H...H"], {"M":"#c8922a","U":"#c8922a","C":"#c8922a","H":"#c8922a"}); // MUCH

  // 6. PEPE FROG (bottom-left zone)
  drawPattern(g, 12, 545, ["..GGGGGGGGGGGGGGGGGGGGGGGGGGGG..",".GGGGGGGGGGGGGGGGGGGGGGGGGGGGGG.","GGG.GGGGGGGGGGGGGGGGGGGGGGGG.GGG","GG.WGGGGGGGGGGGGGGGGGGGGGGWG.GGG","GG.WGGGGGGGGGGGGGGGGGGGGGGWG.GGG","G.BWWBGGGGGGGGGGGGGGGBWWBG.GGGGG","GBBB.BBGGGGGGGGGGGGGBBB.BBGGGGGG","GBBB.BBGGGGGGGGGGGGGBBB.BBGGGGGG","G.BWWBGGGGGGGGGGGGGGBWWBGGGGGGG.","GG..GGGGGGGGGGGGGGGGGGGGGGGGGGG.",".GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG",".GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG",".GG.NNNNN.GGGGGGGGGGNNNNNN.GGG..",".GG.NNNNN.GGGGGGGGGGNNNNNN.GGG..",".GGGGGGGGGGGGGGGGGGGGGGGGGGGGG..","..GGGGGGGGGGGGGGGGGGGGGGGGGGG...","..GLLLLLLLLLLLLLLLLLLLLLLLLLG...","..GGLLLLLLLLLLLLLLLLLLLLLLGGG...","..GGGGGGGGGGGGGGGGGGGGGGGGGGG...","..GWWWWWWWWWWWWWWWWWWWWWWWWGGG.","..GWWWWWWWWWWWWWWWWWWWWWWWWGGG.","..GWWRRRRRRRRRRRRRRRRRRRRRWWGGG.","..GWWRRRRRRRRRRRRRRRRRRRRRWWGGG.","...GWWWWWWWWWWWWWWWWWWWWWWGGGGG","....GGGGGGGGGGGGGGGGGGGGGGGGGG..",".....GGGGGGGGGGGGGGGGGGGGGGG...."], {"G":"#3d9a3d","W":"#f0f0f0","B":"#222","N":"#2d7a2d","L":"#1a5a1a","R":"#cc2200"}); // Pepe frog
  drawPattern(g, 20, 790, ["K...K.EEE.K...K.W...W","K..K..E...K..K..W...W","KKK...EEE.KKK...W.W.W","K..K..E...K..K..W.W.W","K...K.EEE.K...K..W.W."], {"K":"#3d9a3d","E":"#3d9a3d","W":"#3d9a3d"}); // KEKW
  drawPattern(g, 15, 900, ["NNN.GGG.MMM.III","N.N.G.G.M.M..I.","NNN.GGG.MMM..I.","N.N.G.G.M.M..I.","N.N.GGG.M.M.III"], {"N":"#3d9a3d","G":"#3d9a3d","M":"#3d9a3d","I":"#3d9a3d"}); // NGMI

  // 7. CZ PORTRAIT (BNB zone, bottom-right)
  drawPattern(g, 680, 685, [".....KKKKKKKKKKKKKKKKKKKKKK.....","...KKKKKKKKKKKKKKKKKKKKKKKKKKK..","..KKKKKKKKKKKKKKKKKKKKKKKKKKKK..",".KKKKKKKKKKKKKKKKKKKKKKKKKKKKK..","KKKKKKSSSSSSSSSSSSSSSSSSSSSSKKK.","KSSSSSSSSSSSSSSSSSSSSSSSSSSSSSK.","KSSSSSSBBBBBBBBSSSBBBBBBBSSSSSSK","KSSSSBBBB....BBBSBB....BBBBSSSSK","KSSSSBB..EE..BBBSBB..EE..BBSSSK.","KSSSSBB..EE..BBBSBB..EE..BBSSSK.","KSSSSSSBBBBBBBBSSSBBBBBBSSSSSSK.","KSSSSSSSSSSSSSSSSSSSSSSSSSSSSK..","KSSSSSSSSS.NNNN.SSSSSSSSSSSSSK..","KSSSSSSSSSSNNNN.SSSSSSSSSSSSSK..","KSSSSSSSSSSSSSSSSSSSSSSSSSSSSK..","KSSSSSSSSYYYYYYYYYYSSSSSSSSSSKK.","KSSSSSSSSYYYYYYYYYYSSSSSSSSSSKK.","KSSSSSSSSSSSSSSSSSSSSSSSSSSSSK..","KGGGGGGGGGGGGGGGGGGGGGGGGGGGK...",".KGGGGGGGGGGGGGGGGGGGGGGGGGK....","..KGGGGGGGGGGGGGGGGGGGGGGGK.....","...KGGGGGGGGGGGGGGGGGGGGGK......","....KKKKKKKKKKKKKKKKKKKKK.......",".....KKKKKKKKKKKKKKKKKKK........"], {"K":"#1a1000","S":"#ffe0c8","B":"#222","E":"#335577","N":"#bb8844","Y":"#f7c948","G":"#f3ba2f"}); // CZ portrait
  drawPattern(g, 838, 700, [".....YYYY.....","....YYYYYY....","...YYYYYYYY...","..YYYYY.YYYYY.",".YYYY.....YYYY","YYY.........YY",".YYYY.....YYYY","..YYYYYYYYYYYY","...YYYYYYYYYY.","....YYYYYYYY..",".....YYYYYY...","......YYYY....",".......YY....."], {"Y":"#f3ba2f",".":" "}); // BNB diamond
  drawPattern(g, 843, 825, ["BBB.NNN.BBB","B.B.N.N.B.B","BBB.NNN.BBB","B.B.N.N.B.B","BBB.NNN.BBB"], {"B":"#f3ba2f","N":"#f3ba2f"}); // BNB label
  drawPattern(g, 695, 900, ["W...W.AAA.GGG.MMM.III","W...W.A.A.G.G.M.M..I.","W.W.W.AAA.GGG.MMM..I.","W.W.W.A.A.G.G.M.M..I.",".W.W..A.A.GGG.M.M.III"], {"W":"#f3ba2f","A":"#f3ba2f","G":"#f3ba2f","M":"#f3ba2f","I":"#f3ba2f"}); // WAGMI

  // 8. SOLANA LOGO (bottom-center)
  drawPattern(g, 330, 540, ["PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP","PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP..","............................................................................................................................................","GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG","GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG..","............................................................................................................................................","PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP","PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP.."], {"P":"#9945ff","G":"#14f195",".":" "}); // SOL bars
  drawPattern(g, 330, 565, ["SSS.OOO.LLL.AAA.NNN.AAA","S...O.O.L...A.A.N.N.A.A","SSS.O.O.L...AAA.NNN.AAA","S...O.O.L...A.A.N.N.A.A","SSS.OOO.LLL.A.A.N.N.A.A"], {"S":"#9945ff","O":"#9945ff","L":"#9945ff","A":"#14f195","N":"#14f195"}); // SOLANA text

  // 9. CENTER BATTLEFIELD
  drawPattern(g, 340, 255, ["..DDDDD..DDDDD..",".D.....DD.....D.","D...DDD..DDD...D","D..D........D..D",".D..DDDDDDDD..D.","..DDDDDDDDDDDD..","...DDDDDDDDDD...","....DDDDDDDD....",".....DDDDDD.....","......DDDD......",".......DD......."], {"D":"#60d0f0"}); // diamond hands
  drawPattern(g, 375, 250, ["LLL.FFF.GGG","L...F...G.G","LLL.FFF.GGG","L...F...G.G","LLL.F...GGG"], {"L":"#00ff88","F":"#00ff88","G":"#00ff88"}); // LFG
  drawPattern(g, 350, 415, ["....MMM.....","..MMMMMMM...",".MMMMMMMMMM.","MMMM.MMMMMMM","MMM...MMMMMM","MM.....MMMMM","MMM...MMMMMM","MMMM.MMMMMMM",".MMMMMMMMMM.","..MMMMMMMMM.","....MMMMM...",".....MMM...."], {"M":"#f5f5a0"}); // moon
  drawPattern(g, 340, 370, ["TTT.OOO..TTT.HHH.EEE..MMM.OOO.OOO.NNN","T...O.O..T...H.H.E...M.M.O.O.O.O.N.N.","T...O.O..T...HHH.EEE.M.M.O.O.O.O.NNN.","T...O.O..T...H.H.E...M.M.O.O.O.O.N.N.","T...OOO..T...H.H.EEE.M.M.OOO.OOO.N.N."], {"T":"#ffd700","O":"#ffd700","H":"#ffd700","E":"#ffd700","M":"#ffd700","N":"#ffd700"}); // TO THE MOON

  // 10. ACCENT PIECES
  drawPattern(g, 30, 450, ["NNN.FFF.AAA","N.N.F...A.A","NNN.FFF.AAA","N.N.F...A.A","N.N.F...A.A"], {"N":"#f59e0b","F":"#f59e0b","A":"#f59e0b"}); // NFA
  drawPattern(g, 95, 450, ["DDD.Y.Y.OOO.R.R","D.D..Y..O.O.RRR","D.D..Y..O.O.R.R","D.D..Y..O.O.R.R","DDD..Y..OOO.R.R"], {"D":"#f59e0b","Y":"#f59e0b","O":"#f59e0b","R":"#f59e0b"}); // DYOR
  drawPattern(g, 323, 65, ["RRRRR....RRRRR","RRRRR....RRRRR"], {"R":"#ff0000"}); // laser eyes
  drawPattern(g, 545, 250, [".*.","*.*",".*."], {"*":"#c084fc"}); // star
  drawPattern(g, 600, 280, [".*.","*.*",".*."], {"*":"#c084fc"}); // star
  drawPattern(g, 560, 300, [".*.","*.*",".*."], {"*":"#c084fc"}); // star
  drawPattern(g, 620, 240, [".*.","*.*",".*."], {"*":"#c084fc"}); // star
  drawPattern(g, 580, 320, [".*.","*.*",".*."], {"*":"#c084fc"}); // star
  drawPattern(g, 640, 290, [".*.","*.*",".*."], {"*":"#c084fc"}); // star
  drawPattern(g, 700, 260, [".*.","*.*",".*."], {"*":"#c084fc"}); // star
  drawPattern(g, 370, 480, ["GGG.MMM","G.G.M.M","GGG.MMM","G.G.M.M","GGG.M.M"], {"G":"#3d9a3d","M":"#3d9a3d"}); // GM Pepe
  drawPattern(g, 330, 460, ["RRR.EEE.K.K.TTT","R.R.E...K.K..T.","RRR.EEE.KK...T.","R.R.E...K.K..T.","R.R.EEE.K.K..T."], {"R":"#ff4444","E":"#ff4444","K":"#ff4444","T":"#ff4444"}); // REKT
  drawPattern(g, 330, 600, ["AAA.PPP.EEE..III.NNN","A.A.P.P.E....I..N.N.","AAA.PPP.EEE..I..NNN.","A.A.P...E....I..N.N.","A.A.P...EEE.III.N.N."], {"A":"#14f195","P":"#14f195","E":"#14f195","I":"#14f195","N":"#14f195"}); // APE IN
  drawPattern(g, 530, 700, ["PPP.U.U.MMM.PPP","P.P.U.U.M.M.P.P","PPP.U.U.MMM.PPP","P...U.U.M.M.P..","P...UUU.M.M.P.."], {"P":"#f3ba2f","U":"#f3ba2f","M":"#f3ba2f"}); // PUMP
  drawPattern(g, 415, 240, ["TTTTTTTTTTTTTTTTTTTT","T..................T","T..BB.......BB.....T","T.BBBB.....BBBB....T","T..BB.......BB.....T","T..................T","T...PPPPPPPPPP.....T","T.P.PPPPPPPPPP.P...T","T..................T","TTTTTTTTTTTTTTTTTTTT"], {"T":"#888","B":"#333","P":"#cc6666"}); // troll face

  // 11. ZONE BORDERS — contested pixels
  px(g, 499, 0, "#333"); px(g, 500, 0, "#333"); px(g, 501, 0, "#333");
  px(g, 499, 10, "#555"); px(g, 500, 10, "#555"); px(g, 501, 10, "#555");
  px(g, 499, 20, "#333"); px(g, 500, 20, "#333"); px(g, 501, 20, "#333");
  px(g, 499, 30, "#555"); px(g, 500, 30, "#555"); px(g, 501, 30, "#555");
  px(g, 499, 40, "#333"); px(g, 500, 40, "#333"); px(g, 501, 40, "#333");
  px(g, 499, 50, "#555"); px(g, 500, 50, "#555"); px(g, 501, 50, "#555");
  px(g, 499, 60, "#333"); px(g, 500, 60, "#333"); px(g, 501, 60, "#333");
  px(g, 499, 70, "#555"); px(g, 500, 70, "#555"); px(g, 501, 70, "#555");
  px(g, 499, 80, "#333"); px(g, 500, 80, "#333"); px(g, 501, 80, "#333");
  px(g, 499, 90, "#555"); px(g, 500, 90, "#555"); px(g, 501, 90, "#555");
  px(g, 499, 100, "#333"); px(g, 500, 100, "#333"); px(g, 501, 100, "#333");
  px(g, 499, 110, "#555"); px(g, 500, 110, "#555"); px(g, 501, 110, "#555");
  px(g, 499, 120, "#333"); px(g, 500, 120, "#333"); px(g, 501, 120, "#333");
  px(g, 499, 130, "#555"); px(g, 500, 130, "#555"); px(g, 501, 130, "#555");
  px(g, 499, 140, "#333"); px(g, 500, 140, "#333"); px(g, 501, 140, "#333");
  px(g, 499, 150, "#555"); px(g, 500, 150, "#555"); px(g, 501, 150, "#555");
  px(g, 499, 160, "#333"); px(g, 500, 160, "#333"); px(g, 501, 160, "#333");
  px(g, 499, 170, "#555"); px(g, 500, 170, "#555"); px(g, 501, 170, "#555");
  px(g, 499, 180, "#333"); px(g, 500, 180, "#333"); px(g, 501, 180, "#333");
  px(g, 499, 190, "#555"); px(g, 500, 190, "#555"); px(g, 501, 190, "#555");
  px(g, 499, 200, "#333"); px(g, 500, 200, "#333"); px(g, 501, 200, "#333");
  px(g, 499, 210, "#555"); px(g, 500, 210, "#555"); px(g, 501, 210, "#555");
  px(g, 499, 220, "#333"); px(g, 500, 220, "#333"); px(g, 501, 220, "#333");
  px(g, 499, 230, "#555"); px(g, 500, 230, "#555"); px(g, 501, 230, "#555");
  px(g, 499, 240, "#333"); px(g, 500, 240, "#333"); px(g, 501, 240, "#333");
  px(g, 499, 250, "#555"); px(g, 500, 250, "#555"); px(g, 501, 250, "#555");
  px(g, 499, 260, "#333"); px(g, 500, 260, "#333"); px(g, 501, 260, "#333");
  px(g, 499, 270, "#555"); px(g, 500, 270, "#555"); px(g, 501, 270, "#555");
  px(g, 499, 280, "#333"); px(g, 500, 280, "#333"); px(g, 501, 280, "#333");
  px(g, 499, 290, "#555"); px(g, 500, 290, "#555"); px(g, 501, 290, "#555");
  px(g, 499, 300, "#333"); px(g, 500, 300, "#333"); px(g, 501, 300, "#333");
  px(g, 499, 310, "#555"); px(g, 500, 310, "#555"); px(g, 501, 310, "#555");
  px(g, 499, 320, "#333"); px(g, 500, 320, "#333"); px(g, 501, 320, "#333");
  px(g, 499, 330, "#555"); px(g, 500, 330, "#555"); px(g, 501, 330, "#555");
  px(g, 499, 340, "#333"); px(g, 500, 340, "#333"); px(g, 501, 340, "#333");
  px(g, 499, 350, "#555"); px(g, 500, 350, "#555"); px(g, 501, 350, "#555");
  px(g, 499, 360, "#333"); px(g, 500, 360, "#333"); px(g, 501, 360, "#333");
  px(g, 499, 370, "#555"); px(g, 500, 370, "#555"); px(g, 501, 370, "#555");
  px(g, 499, 380, "#333"); px(g, 500, 380, "#333"); px(g, 501, 380, "#333");
  px(g, 499, 390, "#555"); px(g, 500, 390, "#555"); px(g, 501, 390, "#555");
  px(g, 499, 400, "#333"); px(g, 500, 400, "#333"); px(g, 501, 400, "#333");
  px(g, 499, 410, "#555"); px(g, 500, 410, "#555"); px(g, 501, 410, "#555");
  px(g, 499, 420, "#333"); px(g, 500, 420, "#333"); px(g, 501, 420, "#333");
  px(g, 499, 430, "#555"); px(g, 500, 430, "#555"); px(g, 501, 430, "#555");
  px(g, 499, 440, "#333"); px(g, 500, 440, "#333"); px(g, 501, 440, "#333");
  px(g, 499, 450, "#555"); px(g, 500, 450, "#555"); px(g, 501, 450, "#555");
  px(g, 499, 460, "#333"); px(g, 500, 460, "#333"); px(g, 501, 460, "#333");
  px(g, 499, 470, "#555"); px(g, 500, 470, "#555"); px(g, 501, 470, "#555");

}





export default function Play() {
  const canvasRef   = useRef<HTMLCanvasElement>(null);
  const gridRef     = useRef<(PxData|null)[]>(Array(GRID*GRID).fill(null));
  const ownedRef    = useRef(0);

  const [color,     setColor]     = useState(PALETTE[6]);
  const [balance,   setBalance]   = useState(0);
  const [owned,     setOwned]     = useState(0);
  const [placed,    setPlaced]    = useState(0);
  const [strike,    setStrike]    = useState<{tier:StrikeTier;earn:number}|null>(null);
  const [hovered,   setHovered]   = useState<{x:number;y:number;d:PxData|null}|null>(null);
  const [log,       setLog]       = useState<string[]>(["[CANVAS] Click any pixel to place."]);
  const [walletConnected, setWalletConnected] = useState(false);
  const [connecting, setConnecting] = useState(false);
  const [sol,       setSol]       = useState(SOL_START);
  const [bucket,    setBucket]    = useState(36253);       // $CANVAS jackpot
  const [solWin,    setSolWin]    = useState<{mult:number;label:string;amount:number}|null>(null);
  const [bucketWin, setBucketWin] = useState<number|null>(null);
  const [betIdx,    setBetIdx]    = useState<BetIdx>(0);   // 0=0.01, 1=0.1, 2=1 SOL

  // ── Pixel-placement animation overlay ─────────────────────────────────────
  type AnimEntry = { x:number; y:number; color:string; tier:StrikeTier|'none'; start:number; dur:number; };
  const overlayRef = useRef<HTMLCanvasElement>(null);
  const animsRef   = useRef<AnimEntry[]>([]);
  const rafRef     = useRef<number>(0);

  const draw = useCallback(() => {
    const c = canvasRef.current; if(!c) return;
    const ctx = c.getContext("2d")!;
    const img = ctx.createImageData(GRID, GRID);
    const buf = img.data;
    for (let i = 0; i < GRID*GRID; i++) {
      const p = gridRef.current[i];
      const off = i * 4;
      if (p) {
        const hex = p.color.replace("#","");
        buf[off]   = parseInt(hex.slice(0,2),16);
        buf[off+1] = parseInt(hex.slice(2,4),16);
        buf[off+2] = parseInt(hex.slice(4,6),16);
        buf[off+3] = 255;
      } else {
        buf[off]=15; buf[off+1]=15; buf[off+2]=30; buf[off+3]=255;
      }
    }
    ctx.putImageData(img, 0, 0);
  },[]);

  // Seed canvas with preset artwork
  useEffect(() => {
    const g = gridRef.current;
    seedCanvas(g);
    draw();
  },[draw]);

  // Timer: hold rewards + bucket growth
  useEffect(() => {
    const t = setInterval(() => {
      setBalance(b => b + ownedRef.current * HOLD_REWARD_RATE);
      // Bucket grows ~0.5 $CANVAS/sec (simulates global activity)
      setBucket(bk => bk + 0.5);
    }, 1000);
    return () => clearInterval(t);
  },[]);

  // Bot activity
  useEffect(() => {
    const t = setInterval(() => {
      const g = gridRef.current;
      const idx = Math.floor(Math.random()*GRID*GRID);
      const cell = g[idx];
      if (cell?.owner === WALLET) return;
      const newOwner = rndOwner();
      const newColor = PALETTE[Math.floor(Math.random()*PALETTE.length)];
      g[idx] = { color:newColor, owner:newOwner };
      const c = canvasRef.current; if(!c) return;
      const ctx = c.getContext("2d")!;
      const img3 = ctx.createImageData(1, 1);
      const hex3 = newColor.replace("#","");
      img3.data[0]=parseInt(hex3.slice(0,2),16); img3.data[1]=parseInt(hex3.slice(2,4),16);
      img3.data[2]=parseInt(hex3.slice(4,6),16); img3.data[3]=255;
      ctx.putImageData(img3, idx%GRID, Math.floor(idx/GRID));
    }, 300);
    return () => clearInterval(t);
  },[]);

  const handleClick = useCallback((e: React.MouseEvent<HTMLCanvasElement>) => {
    const bet = BET_TIERS[betIdx];
    if (sol < bet.sol) {
      setLog(l => [`[BROKE] Need ${bet.sol} SOL · top up wallet`, ...l.slice(0,11)]);
      return;
    }
    const rect2 = (e.target as HTMLCanvasElement).getBoundingClientRect();
    const gx = Math.floor((e.clientX-rect2.left)/PX);
    const gy = Math.floor((e.clientY-rect2.top)/PX);
    if (gx<0||gy<0||gx>=GRID||gy>=GRID) return;
    const g = gridRef.current;
    const c = canvasRef.current; if(!c) return;
    const ctx = c.getContext("2d")!;

    // Deduct full bet cost upfront
    setSol(s => s - bet.sol);

    let totalEarn = 0;
    let newOwned = 0;
    let bestTier: StrikeTier = "none";
    let bestEarn = 0;
    let totalSolReturn = 0;
    let bestPrize: { mult: number; label: string } | null = null;
    let bucketFeed = 0;
    const pixelBetShare = bet.sol / bet.pixels;

    // Place drawCount pixels in a cluster around (gx, gy)
    const radius = Math.ceil(Math.sqrt(bet.pixels));
    let placed2 = 0;
    for (let dy = -radius; dy <= radius && placed2 < bet.pixels; dy++) {
      for (let dx = -radius; dx <= radius && placed2 < bet.pixels; dx++) {
        const px = gx + dx, py = gy + dy;
        if (px < 0 || py < 0 || px >= GRID || py >= GRID) continue;
        const pidx = py * GRID + px;
        const prev = g[pidx];
        if (!prev || prev.owner !== WALLET) newOwned++;
        g[pidx] = { color, owner: WALLET };

        const img4 = ctx.createImageData(1, 1);
        const hex4 = color.replace("#","");
        img4.data[0]=parseInt(hex4.slice(0,2),16); img4.data[1]=parseInt(hex4.slice(2,4),16);
        img4.data[2]=parseInt(hex4.slice(4,6),16); img4.data[3]=255;
        ctx.putImageData(img4, px, py);

        const tier = rollStrike();
        const earn = BASE_EARN * strikeBonus(tier);
        totalEarn += earn;
        bucketFeed += earn * BUCKET_FEED_PCT;
        if (tier !== "none" && strikeBonus(tier) > strikeBonus(bestTier)) {
          bestTier = tier; bestEarn = earn;
        }

        const prize = rollSolPrize();
        const solReturn = prize.mult * pixelBetShare;
        totalSolReturn += solReturn;
        if (!bestPrize || prize.mult > bestPrize.mult) bestPrize = prize;

        if (dx === 0 && dy === 0) spawnAnim(px, py, color, tier);
        placed2++;
      }
    }

    // Batch state updates
    if (newOwned > 0) setOwned(o => { ownedRef.current = o + newOwned; return o + newOwned; });
    setPlaced(p => p + placed2);
    setBalance(b => b + totalEarn);

    if (totalSolReturn > 0) {
      setSol(s => s + totalSolReturn);
      if (bestPrize && bestPrize.mult >= 2) {
        setSolWin({ mult: bestPrize.mult, label: bestPrize.label, amount: totalSolReturn });
        setTimeout(() => setSolWin(null), bestPrize.mult >= 5 ? 4000 : 2500);
      }
    }

    if (bestTier !== "none") {
      setStrike({ tier: bestTier, earn: bestEarn });
      setTimeout(() => setStrike(null), 3000);
    }

    setBucket(bk => {
      const newBk = bk + bucketFeed;
      if (Math.random() < BUCKET_WIN_CHANCE) {
        const jackpot = Math.floor(newBk * BUCKET_WIN_PCT);
        setBucketWin(jackpot);
        setTimeout(() => setBucketWin(null), 5000);
        setLog(l => [`[🪣 JACKPOT] You won ${jackpot} $CANVAS from the Bucket!`, ...l.slice(0,11)]);
        setBalance(b => b + jackpot);
        return newBk - jackpot;
      }
      return newBk;
    });

    const netSOL = totalSolReturn - bet.sol;
    const solTag = netSOL > 0
      ? `+${netSOL.toFixed(4)} SOL net`
      : netSOL === 0 ? "break-even" : `${netSOL.toFixed(4)} SOL`;
    const logMsg = bestTier !== "none"
      ? `[STRIKE ${bestTier.toUpperCase()}] ${placed2}px · +${totalEarn} $CANVAS · ${solTag}`
      : `[PLACE] ${placed2}px · +${totalEarn} $CANVAS · ${solTag}`;
    setLog(l => [logMsg, ...l.slice(0,11)]);
  },[betIdx, color, sol]);

  // Animation tick (overlay canvas)
  const tickAnims = useCallback(() => {
    const ov = overlayRef.current; if (!ov) return;
    const ctx = ov.getContext('2d')!;
    ctx.clearRect(0, 0, ov.width, ov.height);
    const now = performance.now();
    animsRef.current = animsRef.current.filter(anim => {
      const t = Math.min(1, (now - anim.start) / anim.dur);
      if (t >= 1) return false;
      const hex = anim.color.replace('#','');
      const r = parseInt(hex.slice(0,2),16);
      const g = parseInt(hex.slice(2,4),16);
      const b = parseInt(hex.slice(4,6),16);
      const cx = anim.x + 0.5, cy = anim.y + 0.5;

      // 1. Instant white flash at pixel
      if (t < 0.25) {
        const ft = t / 0.25;
        ctx.fillStyle = `rgba(255,255,255,${(1-ft)*0.95})`;
        ctx.fillRect(anim.x - 2, anim.y - 2, 5, 5);
      }

      // 2. Expanding rings (3 for normal, +2 for rare, +4 for legendary)
      const numRings = anim.tier==='legendary' ? 7 : anim.tier==='rare' ? 5 : 3;
      const maxR     = anim.tier==='legendary' ? 55 : anim.tier==='rare' ? 38 : 22;
      for (let i = 0; i < numRings; i++) {
        const delay  = i * 0.12;
        const ringT  = Math.max(0, (t - delay) / (1 - delay));
        if (ringT <= 0 || ringT >= 1) continue;
        const radius = ringT * maxR;
        const alpha  = (1 - ringT) * 0.85;
        ctx.beginPath();
        ctx.arc(cx, cy, radius, 0, Math.PI * 2);
        ctx.strokeStyle = `rgba(${r},${g},${b},${alpha})`;
        ctx.lineWidth = 1.5;
        ctx.stroke();
      }

      // 3. Pixel sparks (8 directions, pixel-art squares)
      const numSparks = anim.tier==='legendary' ? 16 : anim.tier==='rare' ? 12 : 8;
      const sparkEnd  = 0.75;
      if (t < sparkEnd) {
        const sT     = t / sparkEnd;
        const maxDst = anim.tier==='legendary' ? 30 : anim.tier==='rare' ? 22 : 14;
        const alpha  = (1 - sT) * 0.9;
        for (let i = 0; i < numSparks; i++) {
          const angle = (i / numSparks) * Math.PI * 2;
          const dist  = sT * maxDst;
          const sz    = Math.max(0.8, 2 * (1 - sT * 0.6));
          ctx.fillStyle = `rgba(${r},${g},${b},${alpha})`;
          ctx.fillRect(cx + Math.cos(angle)*dist - sz/2, cy + Math.sin(angle)*dist - sz/2, sz, sz);
        }
        // interleaved white sparks for "sparkle" feel
        for (let i = 0; i < numSparks; i++) {
          const angle = ((i + 0.5) / numSparks) * Math.PI * 2;
          const dist  = sT * maxDst * 0.7;
          const sz    = Math.max(0.5, 1.2 * (1 - sT));
          ctx.fillStyle = `rgba(255,255,255,${alpha * 0.7})`;
          ctx.fillRect(cx + Math.cos(angle)*dist - sz/2, cy + Math.sin(angle)*dist - sz/2, sz, sz);
        }
      }

      // 4. Radial glow for strikes
      if (anim.tier !== 'none' && t < 0.6) {
        const gT    = t / 0.6;
        const gR    = gT * 70;
        const gA    = (1 - gT) * 0.35;
        const goldR = anim.tier==='legendary' ? '255,215,0' : '139,92,246';
        const grad  = ctx.createRadialGradient(cx, cy, 0, cx, cy, gR);
        grad.addColorStop(0, `rgba(${goldR},${gA})`);
        grad.addColorStop(1, 'rgba(0,0,0,0)');
        ctx.beginPath();
        ctx.arc(cx, cy, gR, 0, Math.PI * 2);
        ctx.fillStyle = grad;
        ctx.fill();
      }

      return true;
    });

    if (animsRef.current.length > 0) {
      rafRef.current = requestAnimationFrame(tickAnims);
    } else {
      overlayRef.current?.getContext('2d')?.clearRect(0,0,GRID*PX,GRID*PX);
    }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const spawnAnim = useCallback((x:number, y:number, color:string, tier:StrikeTier|'none') => {
    const dur = tier==='legendary' ? 1600 : tier==='rare' ? 1100 : 650;
    animsRef.current.push({ x, y, color, tier, start: performance.now(), dur });
    if (animsRef.current.length === 1) {
      rafRef.current = requestAnimationFrame(tickAnims);
    }
  }, [tickAnims]);

  const handleMove = useCallback((e: React.MouseEvent<HTMLCanvasElement>) => {
    const rect2 = (e.target as HTMLCanvasElement).getBoundingClientRect();
    const gx = Math.floor((e.clientX-rect2.left)/PX);
    const gy = Math.floor((e.clientY-rect2.top)/PX);
    if (gx<0||gy<0||gx>=GRID||gy>=GRID) { setHovered(null); return; }
    setHovered({x:gx, y:gy, d:gridRef.current[gy*GRID+gx]});
  },[]);


  const handleConnect = () => {
    setConnecting(true);
    setTimeout(() => {
      setConnecting(false);
      setWalletConnected(true);
      setLog(l => ["[WALLET] Demo_7f4…a9c connected · 0 SOL", ...l.slice(0,11)]);
    }, 1200);
  };

  const isHoldr = owned * 12 >= 10000;
  const holdrProgress = Math.min(100, (owned * 12 / 10000) * 100);

  return (
    <div style={{background:"#070710",minHeight:"100vh",color:"#e2e8f0",fontFamily:"'Share Tech Mono','Courier New',monospace",overflow:"hidden"}}>
      {/* Top bar */}
      <div style={{borderBottom:"1px solid #1e1e3f",padding:"9px 16px",display:"flex",alignItems:"center",justifyContent:"space-between",background:"rgba(7,7,16,0.95)",backdropFilter:"blur(8px)"}}>
        <Link href="/" style={{color:"#a855f7",fontFamily:"'Press Start 2P',monospace",fontSize:11,textDecoration:"none",letterSpacing:2}}>← CANVAS</Link>
        <div style={{display:"flex",alignItems:"center",gap:16}}>
          <div style={{fontSize:10,color:"#334155",background:"#0f0f1a",padding:"4px 12px",borderRadius:4,border:"1px solid #1e1e3f"}}>
            0.01/0.1/1 SOL bets · 1/10/100 pixels · 97% RTP · 🪣 Bucket jackpot
          </div>
          {walletConnected ? (
            <div style={{fontSize:10,display:"flex",alignItems:"center",gap:6,background:"#0f1a0f",border:"1px solid #166534",borderRadius:6,padding:"5px 12px"}}>
              <div style={{width:6,height:6,background:"#22c55e",borderRadius:"50%"}} />
              <span style={{color:"#22c55e"}}>Demo_7f4…a9c</span>
            </div>
          ) : (
            <button onClick={handleConnect} disabled={connecting} style={{
              fontSize:10,padding:"6px 14px",borderRadius:6,fontFamily:"inherit",cursor:"pointer",
              background:connecting?"#1a1a2e":"linear-gradient(135deg,#7c3aed,#a855f7)",
              color:"#fff",border:"none",
            }}>
              {connecting ? "Connecting…" : "🔗 Connect Wallet"}
            </button>
          )}
        </div>
      </div>

      <div style={{display:"flex",height:"calc(100vh - 46px)"}}>
        {/* LEFT PANEL */}
        <div style={{width:188,borderRight:"1px solid #1e1e3f",padding:12,display:"flex",flexDirection:"column",gap:10,flexShrink:0,overflowY:"auto",background:"#070710"}}>
          {/* ── THE BUCKET (jackpot) ─────────────────────────────────────── */}
          <div style={{
            background:"linear-gradient(135deg,#1c0900,#120800)",
            border:"2px solid #f59e0b",
            borderRadius:10,padding:"12px 14px",
            boxShadow:"0 0 24px rgba(245,158,11,0.35)",
            textAlign:"center",
          }}>
            <style>{`
              @keyframes bucketPulse {
                0%,100% { box-shadow: 0 0 24px rgba(245,158,11,0.35); }
                50%      { box-shadow: 0 0 48px rgba(245,158,11,0.70); }
              }
              @keyframes bucketNum {
                0%   { transform:scale(1); }
                30%  { transform:scale(1.12); }
                100% { transform:scale(1); }
              }
            `}</style>
            <div style={{fontSize:10,letterSpacing:3,color:"#92400e",marginBottom:4}}>🪣 THE BUCKET</div>
            <div style={{
              fontSize:28,fontWeight:"bold",color:"#f59e0b",lineHeight:1,
              fontFamily:"'Press Start 2P',monospace",
            }}>{Math.floor(bucket).toLocaleString()}</div>
            <div style={{fontSize:10,color:"#78350f",marginTop:4}}>$CANVAS jackpot</div>
            <div style={{marginTop:8,height:2,background:"#1c0900",borderRadius:1}}>
              <div style={{height:"100%",background:"linear-gradient(90deg,#f59e0b,#fbbf24)",width:"100%",borderRadius:1,opacity:0.4}}/>
            </div>
            <div style={{fontSize:10,color:"#6b4c10",marginTop:5,lineHeight:1.6}}>
              0.5% chance per pixel<br/>Win 10% of bucket
            </div>
          </div>

          {/* SOL Balance */}
          <div style={{background:"#0a120a",border:"1px solid #166534",borderRadius:8,padding:12}}>
            <div style={{fontSize:10,color:"#166534",marginBottom:4,letterSpacing:1}}>◎ SOL BALANCE</div>
            <div style={{fontSize:22,fontWeight:"bold",color:"#22c55e",lineHeight:1}}>{sol.toFixed(4)}</div>
            <div style={{fontSize:10,color:"#166534",marginTop:3}}>
              Bet: {BET_TIERS[betIdx].sol} SOL → {BET_TIERS[betIdx].pixels}px · up to 10× back
            </div>
            <div style={{fontSize:10,color:"#14532d",marginTop:2}}>RTP 97% · 97% avg return</div>
          </div>

          {/* Balance */}
          <div style={{background:"#0d0d1a",border:"1px solid #2d1b69",borderRadius:8,padding:12}}>
            <div style={{fontSize:10,color:"#64748b",marginBottom:4,letterSpacing:1}}>$CANVAS BALANCE</div>
            <div style={{fontSize:26,fontWeight:"bold",color:"#a855f7",lineHeight:1}}>{Math.floor(balance).toLocaleString()}</div>
            {owned > 0 && (
              <div style={{fontSize:10,color:"#6d28d9",marginTop:3}}>
                +{(owned*HOLD_REWARD_RATE*60).toFixed(3)}/min hold
              </div>
            )}
          </div>

          {/* Bet Size */}
          <div style={{background:"#0d0d1a",border:"1px solid #2d1b69",borderRadius:8,padding:12}}>
            <div style={{fontSize:10,color:"#64748b",marginBottom:8,letterSpacing:1}}>BET SIZE</div>
            <div style={{display:"flex",flexDirection:"column",gap:6}}>
              {(BET_TIERS as unknown as typeof BET_TIERS[number][]).map((tier, i) => {
                const active = betIdx === i;
                const canAfford = sol >= tier.sol;
                return (
                  <button key={i} onClick={() => setBetIdx(i as BetIdx)} style={{
                    display:"flex",justifyContent:"space-between",alignItems:"center",
                    padding:"7px 10px",borderRadius:6,cursor:"pointer",
                    border:`1px solid ${active?"#7c3aed":"#1e1e3f"}`,
                    background:active?"linear-gradient(135deg,#1e0a3e,#2d1b69)":"#0a0a14",
                    opacity: canAfford ? 1 : 0.4,
                  }}>
                    <span style={{fontSize:10,color:active?"#a855f7":"#475569",fontWeight:active?"bold":"normal"}}>
                      {tier.label}
                    </span>
                    <span style={{fontSize:10,color:active?"#7c3aed":"#334155",background:"#12121a",
                      padding:"2px 6px",borderRadius:3,border:`1px solid ${active?"#4c1d95":"#1e1e3f"}`}}>
                      {tier.tag}
                    </span>
                  </button>
                );
              })}
            </div>
            <div style={{marginTop:8,fontSize:10,color:"#334155",lineHeight:1.6}}>
              Cost: <span style={{color:"#a855f7"}}>{BET_TIERS[betIdx].sol} SOL</span>
              {" · "}{BET_TIERS[betIdx].pixels} pixel{BET_TIERS[betIdx].pixels>1?"s":""}
            </div>
          </div>

          {/* Stats */}
          <div style={{background:"#0d0d1a",border:"1px solid #1e1e3f",borderRadius:8,padding:12,fontSize:11}}>
            <div style={{color:"#64748b",marginBottom:8,fontSize:10,letterSpacing:1}}>YOUR STATS</div>
            {([
              ["Pixels owned", owned],
              ["Total placed", placed],
            ] as [string,number][]).map(([k,v]) => (
              <div key={k} style={{display:"flex",justifyContent:"space-between",marginBottom:5}}>
                <span style={{color:"#475569"}}>{k}</span>
                <span style={{color:"#22d3ee"}}>{v}</span>
              </div>
            ))}
            <div style={{marginTop:8}}>
              <div style={{display:"flex",justifyContent:"space-between",marginBottom:4}}>
                <span style={{fontSize:10,color:"#475569"}}>Holdr status</span>
                <span style={{fontSize:10,color:isHoldr?"#a855f7":"#334155"}}>{isHoldr?"✓ HOLDR":`${Math.floor(holdrProgress)}%`}</span>
              </div>
              <div style={{height:3,background:"#1e1e2e",borderRadius:2}}>
                <div style={{height:"100%",background:isHoldr?"#a855f7":"#4c1d95",width:`${holdrProgress}%`,borderRadius:2,transition:"width 0.3s"}}/>
              </div>
              {!isHoldr && (
                <div style={{fontSize:10,color:"#334155",marginTop:3}}>need {(10000-Math.floor(owned*12)).toLocaleString()} more $C</div>
              )}
            </div>
          </div>

          {/* Withdraw info */}
          <div style={{background:"#0a0a12",border:"1px solid #1a1a30",borderRadius:8,padding:10,fontSize:10,color:"#334155",lineHeight:1.8}}>
            <div style={{color:"#475569",marginBottom:2,letterSpacing:1,fontSize:10}}>WITHDRAW</div>
            Withdraw anytime to wallet.<br/>
            10% tax → <span style={{color:"#6d28d9"}}>Holdr pool</span><br/>
            Holdrs earn passively from<br/>all ecosystem withdrawals.
          </div>
        </div>

        {/* CANVAS CENTER */}
        <div style={{flex:1,display:"flex",alignItems:"center",justifyContent:"center",position:"relative",overflow:"auto",background:"radial-gradient(ellipse at center,#0d0d20,#070710)"}}>

          {/* Bucket jackpot popup */}
          {bucketWin !== null && (
            <div style={{
              position:"absolute",top:"20%",left:"50%",
              transform:"translate(-50%,0)",
              zIndex:25,textAlign:"center",pointerEvents:"none",
            }}>
              <style>{`
                @keyframes bucketWinIn {
                  0%   { opacity:0; transform:translate(-50%,20px) scale(0.6); }
                  20%  { opacity:1; transform:translate(-50%,-10px) scale(1.15); }
                  80%  { opacity:1; transform:translate(-50%,0) scale(1); }
                  100% { opacity:0; transform:translate(-50%,-20px) scale(0.9); }
                }
              `}</style>
              <div style={{
                padding:"20px 40px",borderRadius:16,
                background:"#1c0900",border:"3px solid #f59e0b",
                boxShadow:"0 0 100px rgba(245,158,11,0.8)",
                fontFamily:"'Press Start 2P',monospace",
                animation:"bucketWinIn 5s ease-out forwards",
              }}>
                <div style={{fontSize:10,color:"#f59e0b",marginBottom:8,letterSpacing:3}}>🪣 BUCKET HIT</div>
                <div style={{fontSize:32,color:"#fbbf24",fontWeight:"bold"}}>+{bucketWin.toLocaleString()}</div>
                <div style={{fontSize:10,color:"#92400e",marginTop:6}}>$CANVAS · 10% of jackpot</div>
              </div>
            </div>
          )}

          {/* SOL Win popup */}
          {solWin !== null && solWin.mult >= 2 && (
            <div style={{
              position:"absolute",bottom:"20%",left:"50%",
              transform:"translate(-50%,0)",
              zIndex:22,textAlign:"center",pointerEvents:"none",
            }}>
              <style>{`
                @keyframes solWinIn {
                  0%   { opacity:0; transform:translate(-50%,20px) scale(0.7); }
                  15%  { opacity:1; transform:translate(-50%,-8px) scale(1.08); }
                  75%  { opacity:1; transform:translate(-50%,0) scale(1); }
                  100% { opacity:0; transform:translate(-50%,-15px) scale(0.9); }
                }
              `}</style>
              <div style={{
                padding:"14px 30px",borderRadius:12,
                background:"#0a150a",border:`2px solid ${solWin.mult>=10?"#22c55e":"#4ade80"}`,
                boxShadow:`0 0 ${solWin.mult>=10?"80px":"40px"} rgba(34,197,94,${solWin.mult>=10?0.8:0.4})`,
                fontFamily:"'Press Start 2P',monospace",
                animation:"solWinIn 2.5s ease-out forwards",
              }}>
                <div style={{fontSize:10,color:"#4ade80",marginBottom:6,letterSpacing:2}}>◎ SOL WIN {solWin.label}</div>
                <div style={{fontSize:24,color:"#22c55e",fontWeight:"bold"}}>+{solWin.amount.toFixed(4)}</div>
                <div style={{fontSize:10,color:"#166534",marginTop:4}}>SOL returned to wallet</div>
              </div>
            </div>
          )}

          {/* Strike popup */}
          {strike && (() => {
            const sc = strikeStyle(strike.tier);
            return (
              <div style={{
                position:"absolute",top:"50%",left:"50%",
                transform:"translate(-50%,-60%)",
                zIndex:20,textAlign:"center",pointerEvents:"none",
              }}>
                <style>{`
                  @keyframes strikeIn {
                    0%   { opacity:0; transform:translate(-50%,-80%) scale(0.5); }
                    20%  { opacity:1; transform:translate(-50%,-55%) scale(1.1); }
                    80%  { opacity:1; transform:translate(-50%,-50%) scale(1); }
                    100% { opacity:0; transform:translate(-50%,-40%) scale(0.9); }
                  }
                `}</style>
                <div style={{
                  padding:"18px 36px",borderRadius:14,
                  background:sc.bg,border:`2px solid ${sc.border}`,
                  boxShadow:`0 0 ${strike.tier==="legendary"?"80px":strike.tier==="rare"?"50px":"30px"} ${sc.shadow}`,
                  fontFamily:"'Press Start 2P',monospace",
                  animation:"strikeIn 3s ease-out forwards",
                }}>
                  <div style={{fontSize:10,color:sc.text,marginBottom:6,letterSpacing:2}}>
                    {strike.tier.toUpperCase()} STRIKE
                  </div>
                  <div style={{fontSize:28,color:"#ffffff",fontWeight:"bold"}}>+{strike.earn}</div>
                  <div style={{fontSize:10,color:sc.text,marginTop:4}}>{strikeBonus(strike.tier)}× base · $CANVAS</div>
                </div>
              </div>
            );
          })()}

          <div style={{position:"relative"}}>

            <canvas
              ref={overlayRef}
              width={GRID*PX}
              height={GRID*PX}
              style={{
                position:"absolute",inset:0,
                pointerEvents:"none",
                imageRendering:"pixelated",
                zIndex:3,
              }}
            />
            <canvas
              ref={canvasRef}
              width={GRID*PX}
              height={GRID*PX}
              onClick={handleClick}
              onMouseMove={handleMove}
              onMouseLeave={() => setHovered(null)}
              style={{
                cursor: "crosshair",
                display:"block",
                imageRendering:"pixelated",
                border:"1px solid #1e1e3f",
                borderRadius:4,
                boxShadow:"0 0 60px rgba(88,28,235,0.15)",
              }}
            />

            {hovered && (
              <div style={{
                position:"absolute",
                left: Math.min(hovered.x*PX+14, GRID*PX-170),
                top:  Math.max(hovered.y*PX-38, 0),
                background:"#0d0d1a",border:"1px solid #2d1b69",
                borderRadius:6,padding:"5px 10px",
                fontSize:10,whiteSpace:"nowrap",pointerEvents:"none",zIndex:5,
              }}>
                ({hovered.x},{hovered.y}) ·{" "}
                {hovered.d
                  ? `${hovered.d.owner===WALLET?"YOUR PIXEL":hovered.d.owner}`
                  : "empty — click to claim"}
                {hovered.d && (
                  <span style={{
                    marginLeft:6,display:"inline-block",width:8,height:8,
                    background:hovered.d.color,borderRadius:2,verticalAlign:"middle",
                  }}/>
                )}
              </div>
            )}
          </div>
        </div>

        {/* RIGHT PANEL */}
        <div style={{width:196,borderLeft:"1px solid #1e1e3f",padding:12,display:"flex",flexDirection:"column",gap:10,flexShrink:0,background:"#070710"}}>
          {/* Color picker */}
          <div>
            <div style={{fontSize:10,color:"#64748b",marginBottom:8,letterSpacing:1}}>COLOR</div>
            <div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:4}}>
              {PALETTE.map(c => (
                <button key={c} onClick={() => setColor(c)} style={{
                  aspectRatio:"1",borderRadius:4,background:c,border:"none",cursor:"pointer",
                  outline:color===c?"2px solid #ffffff":"2px solid transparent",
                  outlineOffset:2,transition:"outline 0.1s",
                }}/>
              ))}
            </div>
            <div style={{marginTop:8,display:"flex",alignItems:"center",gap:6,fontSize:10}}>
              <div style={{width:14,height:14,borderRadius:3,background:color,flexShrink:0,border:"1px solid #2d1b69"}}/>
              <span style={{color:"#475569"}}>{color}</span>
            </div>
          </div>

          {/* Strike tiers */}
          <div style={{background:"#0d0d1a",border:"1px solid #0e2a36",borderRadius:8,padding:10}}>
            <div style={{fontSize:10,color:"#64748b",marginBottom:8,letterSpacing:1}}>STRIKE ODDS</div>
            {[
              {tier:"Common",  chance:"5%",   mult:"5×",   color:"#64748b"},
              {tier:"Rare",    chance:"1%",   mult:"25×",  color:"#22d3ee"},
              {tier:"Legendary",chance:"0.1%",mult:"200×", color:"#f59e0b"},
            ].map(s => (
              <div key={s.tier} style={{display:"flex",justifyContent:"space-between",marginBottom:5,fontSize:10}}>
                <span style={{color:s.color}}>{s.tier}</span>
                <span style={{color:"#334155"}}>{s.chance}</span>
                <span style={{color:s.color,fontWeight:"bold"}}>{s.mult}</span>
              </div>
            ))}
            <div style={{marginTop:6,fontSize:10,color:"#1e3a4f",lineHeight:1.6}}>
              Pyth Entropy RNG · on-chain verifiable
            </div>
          </div>

          {/* Activity log */}
          <div style={{background:"#0d0d1a",border:"1px solid #1e1e3f",borderRadius:8,padding:10,flex:1,overflow:"hidden"}}>
            <div style={{fontSize:10,color:"#64748b",marginBottom:8,letterSpacing:1}}>ACTIVITY LOG</div>
            <div style={{fontSize:10,lineHeight:2,overflow:"hidden"}}>
              {log.slice(0,8).map((l,i) => (
                <div key={i} style={{color:i===0?"#a855f7":"#334155",whiteSpace:"nowrap",overflow:"hidden",textOverflow:"ellipsis"}}>{l}</div>
              ))}
            </div>
          </div>

          {/* Leaderboard */}
          <div style={{background:"#0d0d1a",border:"1px solid #1e1e3f",borderRadius:8,padding:10}}>
            <div style={{fontSize:10,color:"#64748b",marginBottom:10,letterSpacing:1}}>TOP PLAYERS</div>
            {[
              {addr:"0xaf1…c32", px:1284, earn:24680, isYou:false},
              {addr:"0x7a3…b9f", px:963,  earn:18420, isYou:false},
              {addr:WALLET,      px:owned, earn:Math.floor(balance), isYou:true},
              {addr:"0x99d…441", px:312,  earn:6180,  isYou:false},
              {addr:"0xb82…71a", px:148,  earn:2860,  isYou:false},
            ]
            .sort((a,b)=>b.px-a.px)
            .slice(0,5)
            .map((p,i) => (
              <div key={p.addr} style={{
                display:"flex",justifyContent:"space-between",
                marginBottom:6,fontSize:10,
                color:p.isYou?"#a855f7":i===0?"#f59e0b":"#475569",
              }}>
                <span style={{overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap",maxWidth:90}}>
                  {i+1}. {p.addr}
                </span>
                <span style={{flexShrink:0,marginLeft:4}}>{p.px}px</span>
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}
